name: Testing

on: push

env:
  ALLOWED_ORIGIN_PATTERNS: ${{ vars.ALLOWED_ORIGIN_PATTERNS}}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ Git checkout
        uses: actions/checkout@v4

      - name: ðŸ’¾ Install modules
        run: npm ci

      - name: ðŸ§ª Testing
        run: npm test
